# Generated by Django 5.2.17 on 2026-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('BACKEND', 'Backend & Database'), ('FRONTEND', 'Frontend & Mobile'), ('DEVOPS', 'DevOps & Tools'), ('OTHER', 'Other / Hardware / AI')], default='BACKEND', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text="Class icon, misal: 'devicon-python-plain' atau SVG path", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tech Stacks',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organization', 'Organization experience')], default='full-time', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('tech_stacks', models.ManyToManyField(blank=True, related_name='projects', to='main.techstack')),
            ],
        ),
    ]
