# Generated by Django 5.2.17 on 2026-09-12 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_techstack_alter_experience_category_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
