# Generated by Django 5.2.17 on 2026-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
