# Generated by Django 5.2.17 on 2026-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_is_featured_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Link ke live site atau GitHub', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Contoh: Frontend Developer & Deployment Specialist', max_length=150),
        ),
    ]
