# Generated by Django 5.2.17 on 2026-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Backend Framework'), ('DATABASE', 'Database'), ('API', 'API & Integration'), ('FRONTEND', 'Frontend Web'), ('CLOUD', 'Cloud & Hosting'), ('DEVOPS', 'DevOps & CI/CD'), ('AI_ML', 'AI / Machine Learning'), ('LANGUAGE', 'Programming Language')], default='BACKEND', max_length=20),
        ),
    ]
