# Generated by Django 5.2.17 on 2026-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
